schedules:
  timeslots:
    path: /app/src/main/java/ru/tpu/hostel/booking/service/old/schedules/schedules.json

otlp:
  tracing:
    export-enabled: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver